subroutine initialize
    use the_whole_varibles
    implicit none
    integer:: I_r,I_z,i1,i2,nmlid
    real*8  r_resonance,z_resonance,b0_set
    real*8  total_cycles,tau_ion_predicted


    !<4namelist>
    namelist /ini/ &
        & mass_number, &
        & frequency, &
        & runHowManyPeriods, &
        & runRFonWhichPeriod, &
        & np_max, &
        & iswitch_dielectric, &
        & iswitch_analytic_temperature, &
        & k_closure_type, &
        & k_constant, &
        & till_uni, &
        & tipp_uni, &
        & tell_uni, &
        & t2pp_uni, &
        & iswitch_analytic_profile, &
        & iswitch_mcc, &
        & iswitch_antenna_type, &
        & irf_set, &
        & resistance, &
        & i_switch_B0, &
        & max_density_set, &
        & vz0, &
        & vl_in_FDFD, &
        & n_pic, &
        & z_inject_cener, &
        & z_resonance, &
        & outputDir, &
        & b0Dir, &
        & kapDir, &
        & plasmaLoadDir, &
        & iswitch_log
    
    namelist /dev/ &
        & dev_Only4CalMag
    

    call start_ftime


    open(newunit=nmlid, file=trim(nmlfile), status="old")
    read(nmlid, nml=ini)
    close(nmlid)

    open(newunit=nmlid, file=trim(nmlfile), status="old")
    read(nmlid, nml=dev)
    close(nmlid)

    call mkdir_if_not_exist

    !np_max = 10000 !@namelist

    mi=mass_number*mp
    mass_q_i_05=0.5*mi/qi
    q_mass_i=qi/mi

    trf=1/frequency
    
    allocate(np(1:np_max))
    allocate(life_and_ek(1:np_max,1:2))
    life_and_ek=0.
    allocate(ir1_iz1_grid(1:np_max,1:2))
    allocate(x(1:np_max,1:3))
    allocate(v(1:np_max,1:3))
    allocate(v_e(1:np_max,1:3))
    allocate(t_np(1:np_max))
    allocate(x_to_grid(1:np_max,1:2))
    np_loss_rec = np_max
    allocate(xv_loss(1:np_loss_rec,1:7))
    xv_loss=0.


    !iswitch_dielectric=3 !@namelist
    !iswitch_analytic_temperature = 1 !@namelist
    !k_closure_type=2 !@namelist
    !k_closure_type =1: 每一点用 find_kfc 闭合 k_parallel
    !               =0: 每一点用常数 k_constant 闭合 k_parallel
    !               =2: 每一点用自定义的 kap 文件闭合 k_parallel
    !k_constant=20.0d0 !@namelist
    

    !till_uni = 3.0 !@namelist
    !tipp_uni = 3.0 !@namelist
    !tell_uni = 3.0 !@namelist
    !t2pp_uni = 3.0 !@namelist
    ! eV

    !iswitch_analytic_profile = 1 !@namelist
    ! 0: nothing happens
    ! 1: analytic profile is set in fun_fdfd.f90

    !-----------------------discharge set-------------------------------!
    iswitch_display=1; !1--the running state display on screen; 0--write into a dat file
    
    !iswitch_mcc=1 !@namelist
    !0-monte carlo collsion off, 1-on  !energy conservation

    !iswitch_dielectric= 1: 冷等离子体，包含离子和电子电流
    !                    2: 冷等离子体，仅保留电子电流
    !                    3: 热等离子体，离子动力学 + 电子冷响应
    !                    4: 热等离子体，离子和电子都采用动力学响应
    !iswitch_dielectric=3 !@namelist

    use_file_defined_density=0 !0-Gaussian profile; 1- read from file

    !iswitch_antenna_type= 0, single loop
    !                    =-1, left helical
    !                    = 1, right helical
    !                    = 2, half loop
    !                    = 3, Nagoya type-III
    !iswitch_antenna_type=1 !@namelist

    !important: this version only tests i_switch_power_mode=0. !!!

    i_switch_power_mode=0;
    !1:set constant total power; 0: set constant current Irf

    !irf_set=500; !@namelist
    !A    use when i_switch_power_mode=0;

    power=1e3;             !W    use when i_switch_power_mode=1;
    !resistance=1 !@namelist
    !ohm, antenna resistance,   use when i_switch_power_mode=1;

    iswitch_RF2=0        !0 - swtich off RF2
    irf2_set=1.1*irf_set;         !A


    !i_switch_B0=1: uniform b0_ci you specificly set;
    !           =2: load B0 from txt files;
    !           =3: B0 field generated by coils (subroutine background_b0)
    !i_switch_B0=2 ; !@namelist
    b0_set=1;             !T. Note: used only when i_switch_B0=1, i.e., i_switch_B0=2 or 3--not use;

    i_switch_MHD_Te=0;    !1-te_in_FDFD evolution by MHD; 0-te_in_FDFD evolution only by MCC; 2-constant te_in_FDFD
    Te_set=6;            !eV. Note: use only when i_switch_MHD_Te=2

    !max_density_set=1e19 !@namelist
    !m-3, maxium initial plasma density

    ti_ini=3;            !eV , initial teamperature of ion
    te_ini=3;            !eV

    !vz0=1d1; !@namelist
    !m/s, Ion orientation speed

    !vl_in_FDFD = 5e4 !@namelist

    !n_pic=6 !@namelist
    !total number of picture to record, i.e. record data at every td/n_pic

    !td=3.e-3; !@namelist indirect
    !s
    td = trf * howManyPeriods
    ! t_power_on=1e-5; !@namelist
    !s
    t_power_on =  trf * runRFonWhichPeriod
    t_power_end=td*1.1
    dt_trf=1e-2;!when setting dt_trf=0, set dt according to tau_ion_predicted; others, use the value
    tau_ion_predicted=1e-2 !s, Predicted energy constraint time, or an typical ion existing time, used to find dt only when dt_trf=0.
    dt_run_fdfd=10*trf
    t_rec_evolution=1*trf !trf
    t_rec_trajectory=trf/200!trf

    call fdfd_ini
    call grid_ini
    call antenna
    
    r_inject_cener=0.0;    !m, rc, central axial position of inject particle    

    !z_inject_cener=-0.17; !@namelist
    !m, zc, central axial position of inject particle   

    width_ne_r=0.015       !m, rw
    width_ne_z=0.1         !m, zw
    width_ne_source_r=0.005
    width_ne_source_z=0.05
    r_resonance=r_inject_cener !m, radial resonant position,usually set r_resonance=r_inject_cener
    ! z_resonance=za !@namelist 
    !m,  axial resonant position,usually set z_resonance=za
    
    if(use_file_defined_density==1)then
        call set_ne_Te_ini_file
    else
        call set_ne_Te_ini
    endif
    
    call mcc_constant
    
    if(i_switch_B0==2)then
        call load_B0
    elseif(i_switch_B0==3)then
        call background_b0
    else
        b0_DC(:,:,1)=0.
        b0_DC(:,:,2)=0.0D0
        b0_DC(:,:,3)=b0_set;
        b0_DC(:,:,4)=b0_set;
    endif
    B_resonance=2*pi*frequency/q_mass_i

    I_r=minloc(abs(r_resonance-r),1);
    I_z=minloc(abs(z_resonance-z),1);
    if(i_switch_B0==1)then
        B0_correction_factor=0.
    else
        B0_correction_factor=B_resonance/b0_DC(I_r,I_z,4)*1.0
        b0_DC=b0_DC*B0_correction_factor
    endif
    bz_max=maxval(b0_DC(1:2,1:nz,4))
    

    te_ave=te_ini
    ti_ave=ti_ini
    te_2D=te_ini
    te_mhd=te_ini
    om=2*pi*frequency;
    omc2=(om/c)*(om/c)
    iom=i*om*mu0
    
    if(i_switch_power_mode==0)then
        i_now=irf_set
    else
        irf_set=sqrt(power/resistance);
        i_now=irf_set;
    endif

    power_Joule=i_now**2*resistance;  ! W
    nn=max_density_set*0.01;
    
    if(tau_ion_predicted>td)tau_ion_predicted=td !when tau_ion>td, use td
    total_cycles=tau_ion_predicted/trf
    if(dt_trf<1e-10)then
        !set dt (Trf), according to the nature of energy conservation (loss <1%) in the RK4 format
        if(total_cycles<50)then
            dt_trf=5e-2
        elseif(total_cycles<1200)then
            dt_trf=2.5e-2
        elseif(total_cycles<1.5e5)then
            dt_trf=1e-2
        elseif(total_cycles<1.5e6)then
            dt_trf=5e-3
        else
            dt_trf=2.5e-3
        endif
    endif
    
    dt=dt_trf*trf;
    
    vi_ex=sqrt(qe_abs*ti_ini/mi);     !expectation of vi :  average speed
    ve_ex=sqrt(qe_abs*te_ini/me);     !expectation of ve :  average speed
    ek_ion_2D=ti_ini*1.5
    ek_ion_2D_r=ek_ion_2D/1.5
    t_rec_profiles=td/real(n_pic)


    call rec_para
    open (unit=42,file=trim(outputDir)//trim('1time_average.dat'),status='unknown',iostat=ierror)
    open (unit=43,file=trim(outputDir)//trim('1time_trajectory.dat'),status='unknown',iostat=ierror)

    if (iswitch_analytic_profile == 1) then
        call readProfileFromFile
    end if

    if (dev_Only4CalMag==1) then
        stop 'Only for calculating magnetic field, stop after background_b0'
    end if
    call readKapFromFile
end subroutine initialize

subroutine rec_para
    use the_whole_varibles
    implicit none
    real*8:: para(1:40)=0
    para(1)=nr;para(2)=nz;para(3)=max_density_set;para(4)=density_ave;
    para(5)=rs;para(6)=dr;para(7)=rl;para(8)=zs;para(9)=dz;para(10)=zl;
    para(11)=dt;para(12)=td;para(13)=pn; para(14)=i_now;para(15)=power_Joule;para(16)=bz_max;para(17)=B0_correction_factor
    para(18)=i_switch_B0; para(19)=t_rec_evolution; para(20)=np_max;
    para(21)=iswitch_RF2;para(23)=dt;para(24)=td;para(25)=trf;
    para(29)=za;para(30)=ra;
    para(31)=z_inject_cener;para(32)=vi_ex;para(33)=ve_ex;para(34)=B_resonance
    para(35)=mp;para(36)=me;para(37)=n_macro;para(38)=power;para(39)=m_end;para(40)=rp

502 format(e12.4,' ')
    open (unit=75,file=trim(outputDir)//trim('1parameter.dat'),status='unknown',iostat=ierror)
    write (75,502)para
    close(75)
end subroutine rec_para

subroutine set_ne_Te_ini_file
    use the_whole_varibles
    implicit none
    real*8  :: ni_int,volume,ni_bd
    real*8  :: sr(1:nr),sz(1:nz),sr_half(2:nr),sz_half(2:nz)
    
    real*8, allocatable :: ni_custom_profile(:,:)

    integer :: file_unit, read_status
    character(len=100) :: input_filename

    allocate(ni_custom_profile(nrp, nz))

    input_filename = 'plasma_density_for_fortran.dat'
    file_unit = 10
    
    open(unit=file_unit, file=input_filename, status='old', action='read', iostat=read_status)

    if (read_status /= 0) then
        write(*,*) 'FATAL ERROR in set_ne_Te_ini: Cannot open file ', trim(input_filename)
        stop 1
    endif

    write(*,*) 'Reading custom plasma density from: ', trim(input_filename)
    do ir = 1, nrp
        read(file_unit, *, iostat=read_status) (ni_custom_profile(ir, iz), iz = 1, nz)
        if (read_status /= 0) then
            write(*,*) 'FATAL ERROR in set_ne_Te_ini: Error reading data, line:', ir
            stop 2
        endif
    enddo
    
    close(file_unit)
    write(*,*) 'Successfully read custom plasma density file.'


    do ir=1,nr
        do iz=1,nz
            if (ir <= nrp) then
                ni(ir,iz) = ni_custom_profile(ir, iz)
            else
                ni(ir,iz) = ni_bd
            endif
        enddo
    enddo
    
    deallocate(ni_custom_profile)

    do ir = 1, nr
        sr(ir) = sum(ni(ir, 1:nz))
    enddo

    do iz = 1, nz
        sz(iz) = 0.0
        do ir = 1, nr
            ! 乘以 r 是因为柱坐标下的积分元是 2*pi*r*dr*dz
            sz(iz) = sz(iz) + ni(ir, iz) * r(ir) 
        enddo
    enddo
    
    sr(1)=0;sr(nr)=0;
    sz(1)=0;sz(nz)=0;

    te_in_FDFD=te_ini

    sr_half(2:nr)=0.5*(sr(1:nr-1)+sr(2:nr))
    sz_half(2:nz)=0.5*(sz(1:nz-1)+sz(2:nz))
    
    if (maxval(sr_half) > 1.0e-20) sr_half=sr_half/maxval(sr_half)
    if (maxval(sz_half) > 1.0e-20) sz_half=sz_half/maxval(sz_half)

    ir=1;pdf_ne_r(ir)=0;
    ir=2;pdf_ne_r(ir)=pi*((dr*0.5)**2)*sr_half(ir)
    do ir=3,nr-1
        pdf_ne_r(ir)=pdf_ne_r(ir-1)+2*pi*(r2(ir)**2-r2(ir-1)**2)*sr_half(ir)
    enddo
    ir=nr;pdf_ne_r(ir)=pdf_ne_r(ir-1)+2*pi*(r(ir)**2-r2(ir-1)**2)*sr_half(ir)
    pdf_ne_r=pdf_ne_r/maxval(pdf_ne_r) !normalization
    do ir=1,nr
        if(abs(pdf_ne_r(ir)-1.)<1e-20)then
            pdf_ne_r(ir+1:nr)=2.0
            exit
        endif
    enddo

    iz=1;pdf_ne_z(iz)=0.
    iz=2;pdf_ne_z(iz)=0.5*dz*sz_half(iz)
    do iz=3,nz-1
        pdf_ne_z(iz)=pdf_ne_z(iz-1)+dz*sz_half(iz) !
    enddo
    iz=nz;pdf_ne_z(iz)=pdf_ne_z(iz-1)+0.5*dz*sz_half(iz)
    pdf_ne_z=pdf_ne_z/maxval(pdf_ne_z) !normalization

    do iz=1,nz
        if(abs(pdf_ne_z(iz)-1.)<1e-20)then
            pdf_ne_z(iz+1:nz)=2.0
            exit
        endif
    enddo

    pdf_ne_source_r = pdf_ne_r
    pdf_ne_source_z = pdf_ne_z
    
    ds=dr*dz
    ni_int=0.
    max_density_set = maxval(ni)
    
    do iz=1,nz-1
        do ir=1,nrp-1
            ni_int=ni_int+2*pi/max_density_set*1./4.*(ni(ir,iz)*r(ir)+ni(ir+1,iz)*r(ir+1) &
                &               +ni(ir,iz+1)*r(ir)+ni(ir+1,iz+1)*r(ir+1))*ds
        end do
    end do

    volume=pi*rp**2*zl
    ni_ave_ratio=ni_int/volume
    n_macro=volume*ni_ave_ratio*max_density_set/np_max !n_macro=ni_int/np_max
    density_ave=ni_ave_ratio*max_density_set  !m-3

end subroutine set_ne_Te_ini_file

subroutine set_ne_Te_ini
    use the_whole_varibles
    implicit none
    real*8  :: ni_int,volume,ni_bd
    real*8  :: sr(1:nr),sz(1:nz),sr_half(2:nr),sz_half(2:nz)

    ni_bd=1e17; !m-3
    !set initial plasma
    ! Gaussian distribution: ni(r,z)=n0*exp(-r^2/(2*rw^2))*exp(-(z-zc)^2/(2*zw^2))
    ni=1e7; !initial set to avoid null value
    do ir=1,nr
        do iz=1,nz
            !if(i_plasma_region(ir,iz)>0.5)then
            tp1=exp(-(r(ir)-r_inject_cener)**2/(2*width_ne_r**2));
            tp2=exp(-(z(iz)-z_inject_cener)**2/(2*width_ne_z**2));
            ni(ir,iz)=ni_bd+max_density_set*(tp1*tp2);

            !exp distribution
            sr(ir)=1+max_density_set/ni_bd*tp1
            sz(iz)=1+max_density_set/ni_bd*tp2

            !!uniform source term
            !sr(ir)=1
            !sz(iz)=1
            !endif
        enddo
    enddo
    sr(1)=0;sr(nr)=0;
    sz(1)=0;sz(nz)=0;

    !ni=ni;
    te_in_FDFD=te_ini

    sr_half(2:nr)=0.5*(sr(1:nr-1)+sr(2:nr))
    sz_half(2:nz)=0.5*(sz(1:nz-1)+sz(2:nz))
    sr_half=sr_half/maxval(sr_half)
    sz_half=sz_half/maxval(sz_half)

    !PDF: density distribution probability
    ir=1;pdf_ne_r(ir)=0;
    ir=2;pdf_ne_r(ir)=pi*((dr*0.5)**2)*sr_half(ir)
    do ir=3,nr-1
        pdf_ne_r(ir)=pdf_ne_r(ir-1)+2*pi*(r2(ir)**2-r2(ir-1)**2)*sr_half(ir)
    enddo
    ir=nr;pdf_ne_r(ir)=pdf_ne_r(ir-1)+2*pi*(r(ir)**2-r2(ir-1)**2)*sr_half(ir)
    pdf_ne_r=pdf_ne_r/maxval(pdf_ne_r) !normalization
    do ir=1,nr
        if(abs(pdf_ne_r(ir)-1.)<1e-20)then
            pdf_ne_r(ir+1:nr)=2
            exit
        endif
    enddo

    iz=1;pdf_ne_z(iz)=0.
    iz=2;pdf_ne_z(iz)=0.5*dz*sz_half(iz)
    do iz=3,nz-1
        pdf_ne_z(iz)=pdf_ne_z(iz-1)+dz*sz_half(iz) !
    enddo
    iz=nz;pdf_ne_z(iz)=pdf_ne_z(iz-1)+0.5*dz*sz_half(iz)
    pdf_ne_z=pdf_ne_z/maxval(pdf_ne_z) !normalization

    do iz=1,nz
        if(abs(pdf_ne_z(iz)-1.)<1e-20)then
            pdf_ne_z(iz+1:nz)=2
            exit
        endif
    enddo

    !set plasma souce (inject with time)
    !plasma souce in z direction
    !set initial plasma
    ! Gaussian distribution: ni(r,z)=n0*exp(-r^2/(2*rw^2))*exp(-(z-zc)^2/(2*zw^2))
    !pdf_ne_source_r=pdf_ne_r

    do ir=1,nrp
        tp1=exp(-(r(ir)-r_inject_cener)**2/(2*width_ne_r**2)); !exp distribution
        sr(ir)=1+max_density_set/ni_bd*tp1
    enddo
    sr(1)=0;sr(nrp)=0;
    sr_half(2:nrp)=0.5*(sr(1:nrp-1)+sr(2:nrp))
    sr_half(2:nrp)=sr_half(2:nrp)/maxval(sr_half(2:nrp))

    !PDF: density distribution probability
    ir=1;pdf_ne_source_r(ir)=0;
    ir=2;pdf_ne_source_r(ir)=pi*((dr*0.5)**2)*sr_half(ir)
    do ir=3,nrp-1
        pdf_ne_source_r(ir)=pdf_ne_source_r(ir-1)+2*pi*(r2(ir)**2-r2(ir-1)**2)*sr_half(ir)
    enddo
    ir=nrp;pdf_ne_source_r(ir)=pdf_ne_source_r(ir-1)+2*pi*(r(ir)**2-r2(ir-1)**2)*sr_half(ir)
    pdf_ne_source_r=pdf_ne_source_r/maxval(pdf_ne_source_r) !normalization
    do ir=1,nrp
        if(abs(pdf_ne_source_r(ir)-1.)<1e-20)then
            pdf_ne_source_r(ir+1:nrp)=2
            exit
        endif
    enddo


    do iz=1,nz
        tp2=exp(-(z(iz)-z_inject_cener)**2/(2*width_ne_source_z**2));
        sz(iz)=1+max_density_set/ni_bd*tp2
    enddo
    sz_half(2:nz)=0.5*(sz(1:nz-1)+sz(2:nz))
    sz_half=sz_half/maxval(sz_half)

    iz=1;pdf_ne_source_z(iz)=0.
    iz=2;pdf_ne_source_z(iz)=0.5*dz*sz_half(iz)
    do iz=3,nz-1
        pdf_ne_source_z(iz)=pdf_ne_source_z(iz-1)+dz*sz_half(iz) !
    enddo
    iz=nz;pdf_ne_source_z(iz)=pdf_ne_source_z(iz-1)+0.5*dz*sz_half(iz)
    pdf_ne_source_z=pdf_ne_source_z/maxval(pdf_ne_source_z) !normalization

    do iz=1,nz
        if(abs(pdf_ne_source_z(iz)-1.)<1e-20)then
            pdf_ne_source_z(iz+1:nz)=2
            exit
        endif
    enddo

    !normalization
    ds=dr*dz
    ni_int=0.
    do iz=1,nz-1
        do ir=1,nrp-1
            ni_int=ni_int+2*pi/max_density_set*1./4.*(ni(ir,iz)*r(ir)+ni(ir+1,iz)*r(ir+1) &
                &               +ni(ir,iz+1)*r(ir)+ni(ir+1,iz+1)*r(ir+1))*ds
        end do
    end do

    volume=pi*rp**2*zl
    ni_ave_ratio=ni_int/volume
    n_macro=volume*ni_ave_ratio*max_density_set/np_max !n_macro=ni_int/np_max
    density_ave=ni_ave_ratio*max_density_set  !m-3

end subroutine set_ne_Te_ini

subroutine set_ne_Te
    use the_whole_varibles
    implicit none

    ni=1e7;te_in_FDFD=0.2
    do ir=1,nr
        do iz=1,nz
            if(i_plasma_region(ir,iz)>0.5)then
                tp1=exp(-r(ir)**2/(2*width_ne_source_r**2));
                tp2=exp(-(z(iz)-z_inject_cener)**2/(2*width_ne_source_z**2));
                !if(density_2D(ir,iz)>1.)then
                ni(ir,iz)=n_macro*density_2D(ir,iz);        !the area the PIC module not simulate
                te_in_FDFD(ir,iz)=te_2D(ir,iz) !te_low_density*(1.+tp1*tp2)  !the area the PIC module not simulate
                !else
                !    ni(ir,iz)=max_density_set*(tp1*tp2); !m-3  !the area of overlap with the PIC module
                !    te_in_FDFD(ir,iz)=te_low_density*(1.+tp1*tp2)  !eV
                !endif
            endif
        enddo
    enddo
end subroutine set_ne_Te

subroutine power_ini
    use the_whole_varibles
    implicit none
    real*8 :: Ek_i_initial, Ek_e_initial

    Ek_i_initial = 0.
    do ip=1,np_max
        Ek_i_initial = Ek_i_initial + mass_q_i_05*sum(v(ip,1:3)**2)
    enddo
    Ek_e_initial = mass_q_e_05 * sum(v_e(1:np_max,1:3)**2)

    Ek_total_initial_joules = (Ek_i_initial + Ek_e_initial) * n_macro * qe_abs
    Ek_total_last_joules = Ek_total_initial_joules
    
    Ek_loss_cumulative = 0.0
    absorbed_power = 0.0
end subroutine power_ini

subroutine readProfileFromFile
    use the_whole_varibles
    implicit none
    real*8:: plasma_load(1:nr,1:4*nz)

    !load the existing plasma profile data directly.
    !plasma_6.dat is written by record_profiles:
    !1: i_plasma_region
    !2: ni
    !3: te_in_FDFD
    !4: total power_depo_rthz

202 format(<nr>(e12.5,' '))
    open (unit=2006,file=trim(plasmaLoadDir),status='old',action='read',iostat=ierror)
    read (2006,202)plasma_load
    close(2006)

    ni_read(1:nr,1:nz)=plasma_load(1:nr,nz+1:2*nz)

    if(iswitch_display==1)then
        write(*,*)'The plasma density has been loaded.'
    endif
end subroutine readProfileFromFile

    
subroutine readKapFromFile
    use the_whole_varibles
    implicit none

203 format(<nr>(e12.5,' '))
    open (unit=2007,file=trim(kapDir),status='old',action='read',iostat=ierror)
    read (2007,*)kap_ll_read_raw
    close(2007)

    kap_ll_read(1:nr,1:nz)=dcmplx(kap_ll_read_raw(1:nr,1:nz),kap_ll_read_raw(1:nr,nz+1:2*nz))

    if(iswitch_display==1)then
        write(*,*)'The wavenumber has been loaded.'
    endif

end subroutine readKapFromFile

subroutine mkdir_if_not_exist
    use the_whole_varibles
    implicit none

    logical :: dirExists
    integer :: cmdstat
    character(len=600) :: cmd
    inquire(file=trim(outputDir), exist=dirExists)
    if (.not. dirExists) then
        cmd = 'mkdir "' // trim(outputDir) // '"'
        call execute_command_line(trim(cmd), exitstat=cmdstat)
    end if
end subroutine mkdir_if_not_exist
